# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['index']},
        ),
    ]
